### ISSUE TITLE
Screens become unaligned when I start scrolling

### ISSUE THREAD

**Issue by samgermain** [dqisme/vscode-sync-scroll#21]
I try to compare similar methods so that I can reduce duplicate code, so I line them up, and then when I start scrolling, the position moves and they're not aligned anymore

[This video is an example of what happens](https://i.imgur.com/1052Roc.mp4)

**Comment by DudeMcGee** [comment]
I have a similar problem, and we have March 24, 2022. - When I start with two documents side by side, everythings looks fine. The more I scroll down on the right hand side, the more the left hand side lags behind. Thus, when I am on line 212, the difference is about half a line-height: The right hand side is about this height lower, or in other words: The left hand side shows line 212 nearer to the top than the other.

This is not a deal-breaker since the corresponding lines are nicely marked but it is somewhat cosmetically bad and it confuses a bit...

**Comment by dqisme** [comment]
Hey, thanks for your feedbacks. I also found the flaky behaviour on aligning lines precisely when scrolling by mouse. Currently, the aligning algorithm is limited by the JavaScript `setInterval` tick. Sometimes it couldn't catch all the mouse movements that is too fast. In that case, I would suggest that you could try to scroll down to the position by the command "Go to Line/Column..." or by keyboard PageUp/Down. And I assume that even it misaligned, you can get it aligned again after scrolling back and force slightly by mouse, isn't it?
