### ISSUE TITLE
`syncScroll.toggle` vs `syncScroll.changeMode`

### ISSUE THREAD

**Issue by lonix1** [dqisme/vscode-sync-scroll#33]
I just upgraded to today's version.

I had a shortcut for `syncScroll.toggle` which was very convenient.

Now I see I need to bind to `syncScroll.changeMode` instead. However that shows a dropdown with normal / offset / off.

Is there a way to bind to the old behaviour quickly - which I assume is "normal" mode?

**Comment by dqisme** [comment]
Hey @lonix1 Thanks for your question.

The new version is basically to simplify the interaction. Now it will regard the turning off as a mode so that we won't have a very long status bar items since some users complained about that.

I think your question also makes sense, that you need a shortcut to switch the sync scroll conveniently. How about binding the shortcut to change the mode? OFF is mapping to the previous toggling off and NORMAL/OFFSET is mapping to toggling on depends on what mode you usually used previously, by default it was NORMAL.

Feel free to try and looking forward to your further feedback.

**Comment by dqisme** [comment]
@lonix1 Unfortunately no, there is no way for now to turn off the extension except selecting the OFF mode in the dropdown.
